### ISSUE TITLE
Could not find clojure executable

### ISSUE THREAD

**Issue by daslu** [probcomp/metaprob#101]
I cloned master and got the following.
(I tried older versions, and then lein did seem to work.)

`
$ lein repl

clojure.lang.ExceptionInfo: Could not find clojure executable
 at clojure.core$ex_info.invokeStatic (core.clj:4617)
    clojure.core$ex_info.invoke (core.clj:4617)
    lein_tools_deps.env$clojure_exe.invokeStatic (env.clj:22)
    lein_tools_deps.env$clojure_exe.invoke (env.clj:16)
    lein_tools_deps.env$scrape_clojure_env.invokeStatic (env.clj:28)
    lein_tools_deps.env$scrape_clojure_env.invoke (env.clj:24)
    clojure.lang.AFn.applyToHelper (AFn.java:154)
    clojure.lang.AFn.applyTo (AFn.java:144)
    clojure.core$apply.invokeStatic (core.clj:646)
    clojure.core$memoize$fn__5708.doInvoke (core.clj:6107)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    lein_tools_deps.plugin$apply_middleware.invokeStatic (plugin.clj:25)
    lein_tools_deps.plugin$apply_middleware.invoke (plugin.clj:17)
    lein_tools_deps.plugin$resolve_dependencies_with_deps_edn.invokeStatic (plugin.clj:47)
    lein_tools_deps.plugin$resolve_dependencies_with_deps_edn.invoke (plugin.clj:34)
    clojure.lang.Var.invoke (Var.java:379)
    leiningen.core.project$apply_middleware.invokeStatic (project.clj:750)
    leiningen.core.project$apply_middleware.invoke (project.clj:743)
    clojure.core.protocols$naive_seq_reduce.invokeStatic (protocols.clj:62)
    clojure.core.protocols$interface_or_naive_reduce.invokeStatic (protocols.clj:72)
    clojure.core.protocols$fn__6755.invokeStatic (protocols.clj:168)
    clojure.core.protocols/fn (protocols.clj:124)
    clojure.core.protocols$fn__6710$G__6705__6719.invoke (protocols.clj:19)
    clojure.core.protocols$seq_reduce.invokeStatic (protocols.clj:31)
    clojure.core.protocols$fn__6738.invokeStatic (protocols.clj:75)
    clojure.core.protocols/fn (protocols.clj:75)
    clojure.core.protocols$fn__6684$G__6679__6697.invoke (protocols.clj:13)
    clojure.core$reduce.invokeStatic (core.clj:6545)
    clojure.core$reduce.invoke (core.clj:6527)
    leiningen.core.project$apply_middleware.invokeStatic (project.clj:745)
    leiningen.core.project$apply_middleware.invoke (project.clj:743)
    leiningen.core.project$activate_middleware.invokeStatic (project.clj:777)
    leiningen.core.project$activate_middleware.invoke (project.clj:773)
    leiningen.core.project$init_project.invokeStatic (project.clj:902)
    leiningen.core.project$init_project.invoke (project.clj:892)
    leiningen.core.project$read.invokeStatic (project.clj:973)
    leiningen.core.project$read.invoke (project.clj:970)
    leiningen.core.project$read.invokeStatic (project.clj:974)
    leiningen.core.project$read.invoke (project.clj:970)
    leiningen.core.main$_main$fn__5998.invoke (main.clj:397)
    leiningen.core.main$_main.invokeStatic (main.clj:394)
    leiningen.core.main$_main.doInvoke (main.clj:391)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    clojure.lang.Var.invoke (Var.java:379)
    clojure.lang.AFn.applyToHelper (AFn.java:154)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.core$apply.invokeStatic (core.clj:646)
    clojure.main$main_opt.invokeStatic (main.clj:314)
    clojure.main$main_opt.invoke (main.clj:310)
    clojure.main$main.invokeStatic (main.clj:421)
    clojure.main$main.doInvoke (main.clj:384)
    clojure.lang.RestFn.invoke (RestFn.java:436)
    clojure.lang.Var.invoke (Var.java:388)
    clojure.lang.AFn.applyToHelper (AFn.java:160)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.main.main (main.java:37)
`

**Comment by daslu** [comment]
For example, at the branch 20180905-alexlew-metaprob-tutorial, lein seems to work.

**Comment by zane** [comment]
Hey @daslu. Thank you for trying out Metaprob! Have you [installed the Clojure command-line tools](https://github.com/probcomp/metaprob/blob/master/INSTALL.md#install-the-clojure-command-line-tools-and-leiningen)?

**Comment by daslu** [comment]
Hey @zane , thank you for your beautiful work!

Yes, I have installed the clojure command-line tools (under Manjaro Linux).
Now I updated to their current version (linux-install-1.9.0.397), and got a new kind of error.
I will try to dive into it and let you know if I find anything.

Thanks!

`
$ lein repl
If there are a lot of uncached dependencies this might take a while ...
java.lang.NullPointerException: null
 at clojure.tools.deps.alpha.util.maven$make_session.invokeStatic (maven.clj:141)
    clojure.tools.deps.alpha.util.maven$make_session.invoke (maven.clj:138)
    clojure.tools.deps.alpha.extensions.maven$eval1000$fn__1002.invoke (maven.clj:76)
    clojure.lang.MultiFn.invoke (MultiFn.java:243)
    clojure.tools.deps.alpha$expand_deps.invokeStatic (alpha.clj:170)
    clojure.tools.deps.alpha$expand_deps.invoke (alpha.clj:152)
    clojure.tools.deps.alpha$resolve_deps.invokeStatic (alpha.clj:215)
    clojure.tools.deps.alpha$resolve_deps.invoke (alpha.clj:197)
    clojure.lang.AFn.applyToHelper (AFn.java:156)
    clojure.lang.AFn.applyTo (AFn.java:144)
    clojure.core$apply.invokeStatic (core.clj:646)
    clojure.core$memoize$fn__5708.doInvoke (core.clj:6107)
    clojure.lang.RestFn.invoke (RestFn.java:421)
    lein_tools_deps.lein_project$resolve_deps.invokeStatic (lein_project.clj:54)
    lein_tools_deps.lein_project$resolve_deps.invoke (lein_project.clj:50)
    lein_tools_deps.plugin$apply_middleware.invokeStatic (plugin.clj:22)
    lein_tools_deps.plugin$apply_middleware.invoke (plugin.clj:17)
    lein_tools_deps.plugin$apply_middleware.invokeStatic (plugin.clj:25)
    lein_tools_deps.plugin$apply_middleware.invoke (plugin.clj:17)
    lein_tools_deps.plugin$resolve_dependencies_with_deps_edn.invokeStatic (plugin.clj:47)
    lein_tools_deps.plugin$resolve_dependencies_with_deps_edn.invoke (plugin.clj:34)
    clojure.lang.Var.invoke (Var.java:379)
    leiningen.core.project$apply_middleware.invokeStatic (project.clj:750)
    leiningen.core.project$apply_middleware.invoke (project.clj:743)
    clojure.core.protocols$naive_seq_reduce.invokeStatic (protocols.clj:62)
    clojure.core.protocols$interface_or_naive_reduce.invokeStatic (protocols.clj:72)
    clojure.core.protocols$fn__6755.invokeStatic (protocols.clj:168)
    clojure.core.protocols/fn (protocols.clj:124)
    clojure.core.protocols$fn__6710$G__6705__6719.invoke (protocols.clj:19)
    clojure.core.protocols$seq_reduce.invokeStatic (protocols.clj:31)
    clojure.core.protocols$fn__6738.invokeStatic (protocols.clj:75)
    clojure.core.protocols/fn (protocols.clj:75)
    clojure.core.protocols$fn__6684$G__6679__6697.invoke (protocols.clj:13)
    clojure.core$reduce.invokeStatic (core.clj:6545)
    clojure.core$reduce.invoke (core.clj:6527)
    leiningen.core.project$apply_middleware.invokeStatic (project.clj:745)
    leiningen.core.project$apply_middleware.invoke (project.clj:743)
    leiningen.core.project$activate_middleware.invokeStatic (project.clj:777)
    leiningen.core.project$activate_middleware.invoke (project.clj:773)
    leiningen.core.project$init_project.invokeStatic (project.clj:902)
    leiningen.core.project$init_project.invoke (project.clj:892)
    leiningen.core.project$read.invokeStatic (project.clj:973)
    leiningen.core.project$read.invoke (project.clj:970)
    leiningen.core.project$read.invokeStatic (project.clj:974)
    leiningen.core.project$read.invoke (project.clj:970)
    leiningen.core.main$_main$fn__5998.invoke (main.clj:397)
    leiningen.core.main$_main.invokeStatic (main.clj:394)
    leiningen.core.main$_main.doInvoke (main.clj:391)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    clojure.lang.Var.invoke (Var.java:379)
    clojure.lang.AFn.applyToHelper (AFn.java:154)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.core$apply.invokeStatic (core.clj:646)
    clojure.main$main_opt.invokeStatic (main.clj:314)
    clojure.main$main_opt.invoke (main.clj:310)
    clojure.main$main.invokeStatic (main.clj:421)
    clojure.main$main.doInvoke (main.clj:384)
    clojure.lang.RestFn.invoke (RestFn.java:436)
    clojure.lang.Var.invoke (Var.java:388)
    clojure.lang.AFn.applyToHelper (AFn.java:160)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.main.main (main.java:37)
    sun.reflect.NativeMethodAccessorImpl.invoke0 (NativeMethodAccessorImpl.java:-2)
    sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    java.lang.reflect.Method.invoke (Method.java:498)
    org.flatland.drip.Main.invoke (Main.java:117)
    org.flatland.drip.Main.start (Main.java:88)
    org.flatland.drip.Main.main (Main.java:64)
`

**Comment by daslu** [comment]
Updating Leiningen 2.7.1->2.8.1 solved the problem.
Thanks @zane !

**Comment by zane** [comment]
Glad to hear it @daslu! Please join us in #metaprob on Clojurians if you wind up having questions. 🙂
