### ISSUE TITLE
Generate illustrations for use in LaTex, via graphviz, SVG, or the like

### ISSUE THREAD

**Issue by jar600** [probcomp/metaprob#13]
A facility for generating graphviz illustrations of traces, similar to what python metaprob has.

**Comment by zane** [comment]
Can this be closed given what's in @alex-lew's tutorial?

**Comment by alex-lew** [comment]
@jar600 had mentioned wanting some way of creating figures that can be easily incorporated into LaTeX documents, so he may have opinions here? The tutorial does draw vector graphics to an SVG, so it's certainly possible to get from that to TeX, but we haven't done it yet.

**Comment by jar398** [comment]
Yes that's right, graphics (trace diagrams in particular, but really everything) in LaTeX is a requirement. It doesn't have to be via graphviz but graphviz worked very nicely for previous manuscripts. If we close the issue we would have to track this unscheduled task in some other way. I'll change the issue title to reflect the looser requirement.

**Comment by vkmvkmvkmvkm** [comment]
We may need “inclusion in LaTeX” for our PLDI submission in mid November.

SVG is fine if it looks good and we have 
- a test for generating it programmatically
- an example LaTeX doc that includes it, which we are confident builds correctly from within our dev image

Vikash

**Comment by zane** [comment]
This feature is not core to the language itself. Visualization tooling should be allowed to evolve independently. As such this issue should be re-created on a different repository. @vkmvkmvkmvkm, please re-open if we're mistaken.
