### ISSUE TITLE
Declaring probprogs to be opaque to prevent interpretation by any metacircular interpreter

### ISSUE THREAD

**Issue by jar600** [probcomp/metaprob#3]
If a metacircular interpreter interprets code that contains a call to metacircular interpreter #2 (a different one, or the same one), it will simply plow ahead an interpret the source code for MCI #2, creating three levels of interpretation (the JVM interpreting MCI #1 interpreting MIC #2).

I thought this was a problem from the biased coin example, but now I don't know. When, say `trace_choices` calls `interpret`, it simply calls it, it won't interpret it. `interpret` can be interpreted by the JVM, so that doesn't initiate another level of interpretation.

If this were a problem, then it could be fixed by introducing a source-code barrier, call it `opaque`, that would force JVM interpretation and inhibit source code interpretation, whenever there were a choice. `opaque` could be used either on the defining side (so all uses of the MCI would automatically drop to the JVM) or on the consuming side (so each use of the MCI could decide which kind of interpretation it would want).

The question isn't raised by the python version of metaprob because it always uses metacirc-stub.vnts, effectively defining all the MCI names as opaque. That is, the MCIs are never used for anything significant.  In the clojure version, however, the MCIs (in their compiled-to-JVM versions) are doing serious work, because there is no equivalent of the python `propose` module.

`opaque` could have other uses, e.g. speeding up deterministic code by forcing to run under the JVM instead of under an MCI.

Not a critical issue, I think, but not totally sure.

**Comment by zane** [comment]
Fixed by #123.
