### ISSUE TITLE
Controlling trace addresses, and finding locations in traces

### ISSUE THREAD

**Issue by jar398** [probcomp/metaprob#51]
These are two closely related issues so I will put them together. This is a design issue, not yet ready for implementation work.

1. Allow control over the structure of a trace, i.e. over the paths to the values in the trace.

The requirements for this feature come from three places: (a) `map`, (b) `mem`, (c) making user code that manipulates traces less sensitive to changes in the source code, (d) possible future type systems for traces.

The original design, from python-metaprob, was a feature called `with-address` (working in conjunction with `this`). `with-address` worked in the old side-effecty interpreter, but does not currently work in the compositional interpreter.

2. Make it easier for users to find things in traces.

Values might get different paths as the source code changes, but this would not matter so much if values were found (and changed) via some kind of search instead of by manually tracking down the path and putting the path in the code. Such a feature would be reminiscent of jquery in Javascript.

If this worked well enough, we might now have to worry as much about sub-issue 1 above.

One requirement comes from the tutorial, where @alex-lew has written the following:

    (define [sex-adr height-adr salary-adr] (addresses-of tr))

The intent is clear - one wants to give descriptive names to paths, so that the places where they're used are easier to understand - but the execution is problematic, in that `addresses-of` doesn't provide any guarantee of the order in which the paths occur in the result list.

**Comment by zane** [comment]
Fixed by #123.
