### ISSUE TITLE
Switch to clojure-native syntax for variable binding

### ISSUE THREAD

**Issue by jar398** [probcomp/metaprob#59]
This issue follows on from https://github.com/probcomp/metaprob-clojure/issues/8#issuecomment-390740100 . This also relates to #52.

Currently clojure-metaprob uses syntax for variable binding inherited from python-metaprob, specifically `block` and `define` (well, `define` was written `=` in python-metaprob and `block` was written `{....}`, but you get the idea). In informal conversation it has been suggested quite vaguely and without analysis that Metaprob should use clojure syntax for binding, i.e. `let` and `letfn`, and add support for `do` which would just be `block` without the option of `define`.

In my opinion what is needed is a moderately detailed proposal for this: what changes would have to be done to the two implementations (syntax.clj and compositional.clj), exactly?  How hard is it to implement them? What happens to the parse trees (traces, `from-clojure`)? What will their traces look like? What should we do about recursive functions, which are impossible to support properly in clojure (as traces, and without side effects)? Are we really ready to completely jettison python-clojure compatibility (to_clojure.clj), something we haven't completely done yet?

Then there are user-facing questions: Do these changes make the language harder for beginners to understand? Do they make the interpreter harder to read?

I don't recommend proceeding with implementation until we have answers for most of these questions.

**Comment by jar398** [comment]
note that the examples would probably have to change as well, because the traces (and therefore the addresses within the traces) will almost certainly change.

**Comment by zane** [comment]
Fixed by #123.
