### ISSUE TITLE
metaprob.tutorial.jupyter cannot be loaded in some contexts

### ISSUE THREAD

**Issue by zane** [probcomp/metaprob#64]
## Description
`src/metaprob/tutorial/jupyter.clj` requires `clojupyter.misc.display`. Because `clojupyter.misc.display` is a namespace included by the lein-jupyter _plugin_ it is only available in Clojure processes that were started via the plugin. This means that attempting to load the `metaprob.tutorial.jupyter` namespace from Clojure processes started in any other way (most commonly `clj` or `lein repl`) will fail.

There are two ways this could happen:
1. A user not familiar with this issue attempts to require the namespace manually.
1. A user attempts to refresh all the Clojure namespaces using a utility like `clojure.tools.namespace.repl/refresh`.

### Option A
Move `src/metaprob/tutorial` outside of `src` and add an entry like
```
:source-paths ["path/to/tutorial"]
```
to `project.clj`. This means that any `.jar` built with Leiningen will include the tutorial files but not , and as a result anyone using Metaprob from such a `.jar` will still be unable to run `clojure.tools.namespace.repl/refresh`. Probably what we would do in this case is either add another `project.clj` for build configuration or use a `clj`-based method for building such as [`juxt/pack.alpha`](https://github.com/juxt/pack.alpha).

### Option B
Declare an explicit dependency `lein-jupyter` by adding 
```
lein-jupyter {mvn/version "0.1.16"}
```
 to `:deps` in `deps.edn`. This means that all artifacts built by either `lein` or `clj` / `clojure` will include the tutorial, `lein-jupyter`, and its dependencies. This may be desirable, but it will increase the size of the `.jar` file and does place a hard dependency on libraries that Metaprob does not need to function.

## Reproduction steps
Attempt to load the `metaprob.tutorial.jupyter` namespace either explicitly
```
clj -e "(require 'metaprob.tutorial.jupyter)"
```
or via `clojure.tools.namespace.repl/refresh`:
```
clj -Srepro \
    -Sdeps "{:deps {org.clojure/tools.namespace {:mvn/version \"0.2.11\"}}}" \
    -e "(require '[clojure.tools.namespace.repl :refer [refresh]])
        (refresh)"
```

## Expected results
```
nil
```
if the namespace was loaded via `require`.
```
:ok
```
if the namespace was loaded via `clojure.tools.namespace.repl/refresh`.

## Actual results
```
:error-while-loading metaprob.tutorial.jupyter
#error {
 :cause "Could not locate clojupyter/misc/display__init.class or clojupyter/misc/display.clj on classpath."
 :via
 [{:type clojure.lang.Compiler$CompilerException
   :message "java.io.FileNotFoundException: Could not locate clojupyter/misc/display__init.class or clojupyter/misc/display.clj on classpath., compiling:(metaprob/tutorial/jupyter.clj:1:1)"
   :at [clojure.lang.Compiler load "Compiler.java" 7526]}
  {:type java.io.FileNotFoundException
   :message "Could not locate clojupyter/misc/display__init.class or clojupyter/misc/display.clj on classpath."
   :at [clojure.lang.RT load "RT.java" 463]}]
 :trace …}
```

**Comment by zane** [comment]
@alex-lew, do you have opinions about the solutions I outlined above?

**Comment by alex-lew** [comment]
Thanks for tracking this down! Option A sounds slightly better, but neither seems perfect... Would it make sense to move the Jupyter stuff to another repo? I still don’t have a good mental model for how the dependency management all works.

**Comment by zane** [comment]
No worries! I'm still learning about how plugins affect the classpath myself.

Moving the tutorial notebooks to another repository could make sense. We can also just do Option A now and kick this question down the road until we actually start building `.jar`s.
