### ISSUE TITLE
Make sure (length '{}) works

### ISSUE THREAD

**Issue by jar398** [probcomp/metaprob#74]
`(length '{})` needs to yield 0. I don't think there's a test for this in sequence_test.clj. I don't know whether the test would succeed; if not `length` should be fixed.

**Comment by zane** [comment]
Small note: No need to quote the empty map literal. `(= '{} {}) ; true`

**Comment by jar398** [comment]
In clojure. I quote it as a metaprob habit. (maybe we should change metaprob.)

**Comment by alex-lew** [comment]
(quote ...) is not understood by the Metaprob (definitional) interpreter, is it?

**Comment by jar398** [comment]
Absolutely right! Totally forgot.

Maybe this test should be written some other way. `(trace)` would be right if we (that is, I) weren't preserving the option of reverting to `(trace)` evaluating to `()` some time in the future. Maybe there's some expression involving clojure core functions that yields an empty hashmap?  Can't think of one off the top of my head, but I expect there is.

Or, `quote` could be implemented. That's a @vkmvkmvkmvkm question. Fortunately it doesn't affect the interpreter, since it can be elminated in the 'parser' (syntax.clj).
