### ISSUE TITLE
free-vars-approximately mishandles maps

### ISSUE THREAD

**Issue by zane** [probcomp/metaprob#81]
Currently `metaprob.syntax/free-vars-approximately` doesn't descend correctly into maps. 

The intent appears to be for it to recursively descend into nested maps, sequences, and vectors aggregating all the symbols it finds into a set. It doesn't appear to handle maps correctly however. In particular:
1. It appears to attempt to `map` over the key/value pairs, but the function provided to map accepts two arguments rather than a single two-argument tuple. This means that calling `metaprob.syntax/free-vars-approximately` on any non-empty map will trigger an exception.
2. It recurs on the union of the key form and value form, but `metaprob.syntax/free-vars-approximately` will always return `#{}` for any arguments that are not a vector, a sequence, or a map.

**Comment by jar398** [comment]
Note that if this only has to do with maps, the issue is moot (although admittedly not handled well) if the metaprob "parser" doesn't handle maps as well. (haven't studied it)

Damn!  I think that should be 'recurs', not 'recurses'. Damn!
