### ISSUE TITLE
Factor meta-circular interpreter into syntactic processing and semantic processing

### ISSUE THREAD

**Issue by jar398** [probcomp/metaprob#85]
The problem:

Each new meta-circular interpreter reproduces a large amount of common boilerplate, specifically the dispatch on expression type (and therefore knowledge of the expression representation), the sequencing of evaluation, variable binding and lookup (i.e. the beta rule), and much of procedure invocation. This makes changes to the language unwieldy (you have to change all interpreters) and also makes enhancement and creation of new inference techniques cumbersome since code unrelated to inference (e.g. dispatch) has to be intertwined with inference logic.

The solution:

It should be possible to factor the interpreter into syntactic and semantic processing modules. The syntactic phase is outlined above; semantic processing is only _how_, in inference, evaluation of one expression evaluates with evaluation of another, or equivalently how a procedure interacts with the evaluation of its argument.

Given such a factoring, we could get away with only a single syntactic module (unless we wanted to experiment with new syntaxes), and changes to inference - swappable inference cartridges, as it were - would be uncluttered and no bigger than logically necessary.

Techniques for doing this are well known in the functional programming community.

**Comment by jar398** [comment]
Take a look at ev.scm in https://mumble.net/~jar/20160309/monad.tgz

The sequencing is determined in the first pass, but what exactly happens when things are sequenced is 'semantic' and happens in the second pass (run time).

**Comment by zane** [comment]
Metaprob is no longer interpreted as of #123.
