### ISSUE TITLE
Static validation that a given piece of clojure code will be suitable as input to the Metaprob interpreter

### ISSUE THREAD

**Issue by jar398** [probcomp/metaprob#91]
This feature was requested early on by @vkmvkmvkmvkm 

It would be nice if we had a validator that took a source code file (or a function definition?) and checked whether the code was suitable for use as a generative function (i.e. can be 'properly' implemented by a metaprob interpreter).

I'm not sure exactly what this would mean - but mostly that it doesn't use Clojure features like `deftype` that aren't supported by metaprob.  I don't know if it's supposed to work at the file level, or at the level of individual `gen` expressions.  I also don't know if it's supposed to be a separate tool, or part of the clojure `gen` macro (which itself does a prepass over the code, for other reasons). Maybe we can figure this out and add information to the issue conversation, or improve the  issue description.

**Comment by zane** [comment]
Perhaps `clojure.spec` could be useful here. 🤔

**Comment by zane** [comment]
Fixed by #123.
